version: '3.4'

services:
  hurtombotrunner:
    image: ${DOCKER_REGISTRY-}hurtombotrunner
    build:
      context: .
      dockerfile: HurtomBotRunner/Dockerfile

  hurtombotworker:
    image: ${DOCKER_REGISTRY-}hurtombotworker
    build:
      context: .
      dockerfile: HurtomBotWorker/Dockerfile

